language: ruby
services:
 - postgresql
rvm:
 - 2.7.1
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
# uncomment and edit the following line if your project needs to run something other than `rake`:
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
notifications:
  email:
    recipients:
      - joshaidan@gmail.com
    on_failure: change
    on_success: never
